### PR TITLE
Fix bootstrap4 navbar_dropdown helper

### LINKED ISSUE #14: Bootstrap 4: navbar_dropdown not correct
I recently discovered that the `navbar_dropdown` helper for Bootstrap4 is not working as desired.
The syntax changed a bit.

I will open a PR as soon as possible 😄

### PR DESCRIPTION
**Pull request by pabse**
This also adds an `navbar_dropdown_item` helper for the items of a dropdown - obviously.

The helper is necessary, as the item of a dropdown does not use the `navbar-item` class. Instead it uses the `dropdown-item` class.

fixes #14

### CODE REVIEW

File: lib/bootstrap-navbar/helpers/bootstrap4.rb [hunk 1]
```diff
@@ -67,27 +67,37 @@ def navbar_item(text, url = nil, list_item_options = nil, link_options = nil, &b
...
+  <div class="dropdown-menu" aria-labelledby="#{id}">
+    #{capture(&block) if block_given?}
   </div>
 </li>
 HTML
   end
 
+  def navbar_dropdown_item(text, url = nil, link_options = nil, &block)
+    url ||= '#'
+    link_options = link_options ? link_options.dup : {}
```
Comment (manuelmeurer) [inline lib/bootstrap-navbar/helpers/bootstrap4.rb]: Can we move the defaults for `url` and `link_options` to the method signature?

**Comment by manuelmeurer** [comment]
Thanks! One small comment, otherwise I'm happy to merge!

**Comment by pabse** [comment]
Sorry for the late response.
Updated the method signature as you requested 👍
